# Generated by Django 2.2.15 on 2024-05-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke1', models.CharField(max_length=100)),
                ('poke2', models.CharField(max_length=100)),
                ('poke3', models.CharField(max_length=100)),
                ('poke4', models.CharField(max_length=100)),
                ('poke5', models.CharField(max_length=100)),
                ('poke6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('player', models.CharField(max_length=100)),
                ('opponent', models.CharField(max_length=100)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('player_score', models.IntegerField(null=True)),
                ('opp_score', models.IntegerField(null=True)),
                ('player_win', models.BooleanField()),
                ('observations', models.TextField()),
                ('player_team_paste', models.CharField(blank=True, max_length=255, null=True)),
                ('opp_team_paste', models.CharField(blank=True, max_length=255, null=True)),
                ('opp_guild_name', models.CharField(blank=True, max_length=100, null=True)),
                ('opp_team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opponent_team', to='api.Team')),
                ('player_team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Player_team', to='api.Team')),
            ],
        ),
    ]
